"""
Batch scoring module for the bank marketing response model.

Generated by 09_final_model_deployment.ipynb -- do not hand-edit the model
artifacts; re-run the notebook and re-export if the model changes. This
file itself can be edited (it's the deployment wrapper, not a derived
artifact), but keep any changes in sync with what the notebook documents.

Usage (library):
    from predict import score_batch, get_model_info

    call_list = score_batch(new_customers_df, capacity_pct=15)
    info = get_model_info()

Usage (CLI):
    python predict.py customers.csv --capacity-pct 15 --output call_list.csv
    python predict.py customers.csv --min-probability 0.30

Input contract:
    `raw_df` must already be through the same cleaning + feature engineering
    steps as Notebook 03 (duration dropped, contacted_before /
    pdays_known_days / month_sin / month_cos / day_of_week_sin /
    day_of_week_cos / education_ordinal / age_group present). This module
    validates that every column the pipeline was fit on is present and
    fails fast, with the exact missing column names, rather than letting
    scikit-learn raise an opaque error deep inside `.transform()`.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Optional

import joblib
import numpy as np
import pandas as pd

logger = logging.getLogger("bank_marketing_scoring")
if not logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("%(asctime)s | %(levelname)s | %(message)s",
                                             datefmt="%Y-%m-%d %H:%M:%S"))
    logger.addHandler(_handler)
    logger.setLevel(logging.INFO)

_MODEL_DIR = Path(__file__).resolve().parent
_PREPROCESSOR_PATH = _MODEL_DIR / "final_preprocessor.joblib"
_MODEL_PATH = _MODEL_DIR / "final_model.joblib"
_CONFIG_PATH = _MODEL_DIR / "final_model_config.json"


class MissingColumnsError(ValueError):
    """Raised when the input dataframe is missing columns the pipeline needs."""


def _load_artifact(path: Path, label: str):
    if not path.exists():
        raise FileNotFoundError(
            f"{label} not found at {path}. Run 09_final_model_deployment.ipynb "
            "and confirm it exported this file alongside predict.py."
        )
    return joblib.load(path)


_preprocessor = _load_artifact(_PREPROCESSOR_PATH, "Preprocessing pipeline")
_model = _load_artifact(_MODEL_PATH, "Final model")

_raw_feature_names = list(_preprocessor.feature_names_in_)
_encoded_feature_names = [
    name.replace("<", "lt_").replace("[", "(").replace("]", ")")
    for name in _preprocessor.get_feature_names_out()
]
_model_feature_names = list(_model.feature_names_in_)

# The preprocessor (fit in Notebook 04) and the final model (fit in Notebook 07, on top of
# Notebook 05's feature selection) do not necessarily agree on the encoded column set --
# Notebook 05 dropped a near-zero-variance one-hot column (onehot__default_yes, only 3
# training examples) *after* the preprocessor had already been fit, so the preprocessor
# still emits it. Reconciling here, once, means every caller gets a correctly-aligned
# feature matrix automatically instead of a scikit-learn error deep inside .predict_proba().
_extra_in_preprocessor = set(_encoded_feature_names) - set(_model_feature_names)
_missing_from_preprocessor = set(_model_feature_names) - set(_encoded_feature_names)
if _extra_in_preprocessor:
    logger.info("Preprocessor emits %d column(s) the model doesn't use (dropped in feature "
                "selection): %s -- these will be discarded before prediction.",
                len(_extra_in_preprocessor), sorted(_extra_in_preprocessor))
if _missing_from_preprocessor:
    logger.warning("Model expects %d column(s) the preprocessor doesn't emit: %s -- these "
                    "will be filled with 0 (correct only if they're one-hot indicator "
                    "columns for a category absent from this preprocessor's training data).",
                    len(_missing_from_preprocessor), sorted(_missing_from_preprocessor))

try:
    with open(_CONFIG_PATH) as f:
        _model_config = json.load(f)
except FileNotFoundError:
    _model_config = {}
    logger.warning("final_model_config.json not found -- get_model_info() will fall back "
                    "to model introspection only (no validation metrics available).")


def _validate_columns(raw_df: pd.DataFrame) -> None:
    """Fail fast, with the exact missing column names, before scikit-learn does
    something less informative deep inside ColumnTransformer.transform()."""
    missing = [col for col in _raw_feature_names if col not in raw_df.columns]
    if missing:
        raise MissingColumnsError(
            f"Input is missing {len(missing)} column(s) the pipeline requires: {missing}. "
            f"Expected columns: {_raw_feature_names}."
        )
    if raw_df.empty:
        raise ValueError("Input dataframe has 0 rows -- nothing to score.")


def score_batch(
    raw_df: pd.DataFrame,
    capacity_pct: Optional[float] = None,
    min_probability: Optional[float] = None,
) -> pd.DataFrame:
    """Score customers and return a ranked call list.

    Exactly one of `capacity_pct` or `min_probability` should be set:

    - `capacity_pct`: keep only the top N% by predicted probability (a
      call-centre-capacity cutoff). This is the recommended mode --
      Notebook 08 found the target rate drifts substantially across time
      periods, and a percentile cutoff is far more stable to that drift
      than a fixed probability threshold.
    - `min_probability`: keep only rows scoring at or above a fixed
      probability. Only use this once real cost-per-call /
      value-per-subscription figures replace Notebook 08's placeholder
      assumptions -- see that notebook's threshold sensitivity analysis.
    - If neither is set, every row is returned, ranked, unfiltered.

    Raises:
        MissingColumnsError: if `raw_df` is missing a column the fitted
            pipeline expects. The error lists exactly which ones.
        ValueError: if both `capacity_pct` and `min_probability` are given,
            or the input is empty.
    """
    if capacity_pct is not None and min_probability is not None:
        raise ValueError("Pass capacity_pct OR min_probability, not both.")

    _validate_columns(raw_df)
    logger.info("Scoring %d row(s)...", len(raw_df))

    encoded = _preprocessor.transform(raw_df[_raw_feature_names])
    encoded_df = pd.DataFrame(encoded, columns=_encoded_feature_names, index=raw_df.index)
    # Align to exactly the columns the model was trained on (see the reconciliation note
    # above) -- drops columns the model never saw, adds any it expects as all-zero.
    encoded_df = encoded_df.reindex(columns=_model_feature_names, fill_value=0)
    proba = _model.predict_proba(encoded_df)[:, 1]

    out = raw_df.copy()
    out["probability"] = proba
    out["decile"] = pd.qcut(-proba, 10, labels=False, duplicates="drop") + 1
    out = out.sort_values("probability", ascending=False).reset_index(drop=True)
    out.insert(0, "rank", np.arange(1, len(out) + 1))

    if capacity_pct is not None:
        if not 0 < capacity_pct <= 100:
            raise ValueError(f"capacity_pct must be in (0, 100], got {capacity_pct}.")
        k = max(1, int(round(len(out) * capacity_pct / 100)))
        out = out.head(k)
        logger.info("Capacity cutoff: top %.1f%% -> %d of %d customers selected.",
                    capacity_pct, k, len(raw_df))
    elif min_probability is not None:
        if not 0 <= min_probability <= 1:
            raise ValueError(f"min_probability must be in [0, 1], got {min_probability}.")
        n_before = len(out)
        out = out[out["probability"] >= min_probability].reset_index(drop=True)
        logger.info("Probability cutoff >= %.2f -> %d of %d customers selected.",
                    min_probability, len(out), n_before)
    else:
        logger.info("No cutoff applied -- returning all %d scored customers, ranked.", len(out))

    return out


def get_model_info() -> dict:
    """Model metadata for display in a UI or a monitoring dashboard -- combines
    live introspection (always available) with Notebook 08/09's saved
    validation metrics (available once final_model_config.json is exported)."""
    info = {
        "model_type": type(_model).__name__,
        "n_estimators": getattr(_model, "n_estimators", None),
        "max_depth": getattr(_model, "max_depth", None),
        "n_features": len(_model_feature_names),
        "n_raw_input_columns": len(_raw_feature_names),
    }
    info.update(_model_config)
    return info


def get_feature_importance(top_n: int = 15) -> pd.DataFrame:
    """Native feature importance for tree-based models. Returns an empty
    dataframe (not an error) for model types that don't expose it, e.g.
    Logistic Regression -- callers should check `.empty` before plotting."""
    if not hasattr(_model, "feature_importances_"):
        logger.warning("%s has no .feature_importances_ -- returning empty result.",
                        type(_model).__name__)
        return pd.DataFrame(columns=["feature", "importance"])
    importances = pd.DataFrame({
        "feature": _model_feature_names,
        "importance": _model.feature_importances_,
    }).sort_values("importance", ascending=False).head(top_n).reset_index(drop=True)
    return importances


def _build_arg_parser():
    import argparse
    parser = argparse.ArgumentParser(
        description="Score a batch of customers for the term-deposit campaign model.")
    parser.add_argument("input_csv", help="Path to a CSV of customers to score.")
    cutoff = parser.add_mutually_exclusive_group()
    cutoff.add_argument("--capacity-pct", type=float, default=None,
                         help="Keep only the top N%% by predicted probability.")
    cutoff.add_argument("--min-probability", type=float, default=None,
                         help="Keep only rows scoring >= this probability.")
    parser.add_argument("--output", default="call_list.csv", help="Output CSV path.")
    return parser


def main():
    parser = _build_arg_parser()
    args = parser.parse_args()

    input_df = pd.read_csv(args.input_csv)
    result = score_batch(input_df, capacity_pct=args.capacity_pct,
                          min_probability=args.min_probability)
    result.to_csv(args.output, index=False)
    logger.info("Wrote %d row(s) -> %s", len(result), args.output)


if __name__ == "__main__":
    main()
