"""
Batch scoring module for the bank marketing response model.
Generated by 09_Final_Model_Deployment.ipynb -- do not hand-edit; re-run
the notebook and re-export if the model or feature engineering changes.

This module is the ONLY place raw customer data is turned into a
prediction. It reuses `src.features.engineer_features` -- the exact same
function Notebook 03 uses to build the training data -- so training and
production scoring can never silently drift apart. (Earlier versions of
this package had App/app.py re-implement the feature engineering by hand;
that duplication was removed so there is now a single source of truth.)

Usage:
    from predict import score_batch
    call_list = score_batch(new_customers_df, capacity_pct=15)

Input contract for `raw_df`: one row per customer, using the ORIGINAL
raw column names and values straight from the bank's export -- the same
schema as data/raw/bank-additional-full.csv minus the `y` target column
(age, job, marital, education, default, housing, loan, contact, month,
day_of_week, campaign, pdays, previous, poutcome, and the five macro-
economic columns). `duration` may be present or absent; if present it is
dropped automatically (it's a leakage feature, per Notebook 02/03) since
it is only known after a call ends and would not exist yet when scoring
customers to decide who to call.
"""

import sys
from pathlib import Path

import joblib
import pandas as pd

_MODEL_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _MODEL_DIR.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from src.features import engineer_features  # noqa: E402  (path setup must run first)

_preprocessor = joblib.load(_MODEL_DIR / "final_preprocessor.joblib")
_model = joblib.load(_MODEL_DIR / "final_model.joblib")
_feature_names = [n.replace("<", "lt_").replace("[", "(").replace("]", ")")
                   for n in _preprocessor.get_feature_names_out()]

# Columns the preprocessor was fit on (Notebook 04, on Notebook 03's
# engineered feature set). If a future retrain changes Notebook 05's
# feature-selection output and this preprocessor/model pair falls out of
# sync with each other, this check fails loudly at import time instead of
# silently mis-scoring customers or throwing a confusing sklearn shape
# error deep inside predict_proba.
_model_n_features = getattr(_model, "n_features_in_", None)
if _model_n_features is not None and _model_n_features != len(_feature_names):
    raise RuntimeError(
        "final_preprocessor.joblib and final_model.joblib disagree on the "
        f"encoded feature count ({len(_feature_names)} vs {_model_n_features}). "
        "This means the two artifacts were saved from different pipeline "
        "runs. Re-run 09_Final_Model_Deployment.ipynb end-to-end so both "
        "are re-fit and re-saved together, then redeploy -- do not patch "
        "around this here."
    )


def score_batch(raw_df: pd.DataFrame, capacity_pct: float = None) -> pd.DataFrame:
    """
    Score customers and return a ranked call list.

    Parameters
    ----------
    raw_df : pd.DataFrame
        Raw, un-engineered customer data (see module docstring for the
        exact contract). Do NOT pre-apply Notebook 03's feature
        engineering yourself -- this function does that internally via
        `engineer_features`, so passing already-engineered columns
        (e.g. `age_group`, `education_ordinal`) will raise a KeyError.
    capacity_pct : float, optional
        If given, keep only the top capacity_pct% by predicted
        probability (e.g. 15 for the top 15%, matching the operating
        point documented in model_card.json). If omitted, all rows are
        scored and returned, ranked highest-probability first.

    Returns
    -------
    pd.DataFrame
        `raw_df` with `probability` and `decile` columns added, sorted
        by probability descending (and truncated to capacity_pct if set).
    """
    engineered = engineer_features(raw_df)
    encoded = _preprocessor.transform(engineered)
    encoded_df = pd.DataFrame(encoded, columns=_feature_names)

    proba = _model.predict_proba(encoded_df)[:, 1]

    out = raw_df.copy()
    out["probability"] = proba
    out["decile"] = pd.qcut(-proba, 10, labels=False, duplicates="drop") + 1
    out = out.sort_values("probability", ascending=False).reset_index(drop=True)

    if capacity_pct is not None:
        k = max(1, int(len(out) * capacity_pct / 100))
        out = out.head(k)

    return out


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python predict.py <input_csv> [capacity_pct]")
        sys.exit(1)
    input_df = pd.read_csv(sys.argv[1])
    pct = float(sys.argv[2]) if len(sys.argv) > 2 else None
    result = score_batch(input_df, capacity_pct=pct)
    result.to_csv("call_list.csv", index=False)
    print(f"Wrote {len(result)} rows -> call_list.csv")
