"""
Batch scoring module for the bank marketing response model.
Generated by 09_final_model_deployment.ipynb -- do not hand-edit; re-run
the notebook and re-export if the model changes.

Usage:
    from predict import score_batch
    call_list = score_batch(new_customers_df, capacity_pct=15)
"""

import joblib
import pandas as pd
from pathlib import Path

_MODEL_DIR = Path(__file__).resolve().parent
_preprocessor = joblib.load(_MODEL_DIR / "final_preprocessor.joblib")
_model = joblib.load(_MODEL_DIR / "final_model.joblib")
_feature_names = [n.replace("<", "lt_").replace("[", "(").replace("]", ")")
                   for n in _preprocessor.get_feature_names_out()]


def score_batch(raw_df: pd.DataFrame, capacity_pct: float = None) -> pd.DataFrame:
    """Score customers and return a ranked call list. See notebook 09 for details."""
    encoded = _preprocessor.transform(raw_df)
    encoded_df = pd.DataFrame(encoded, columns=_feature_names)

    proba = _model.predict_proba(encoded_df)[:, 1]

    out = raw_df.copy()
    out["probability"] = proba
    out["decile"] = pd.qcut(-proba, 10, labels=False, duplicates="drop") + 1
    out = out.sort_values("probability", ascending=False).reset_index(drop=True)

    if capacity_pct is not None:
        k = max(1, int(len(out) * capacity_pct / 100))
        out = out.head(k)

    return out


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python predict.py <input_csv> [capacity_pct]")
        sys.exit(1)
    input_df = pd.read_csv(sys.argv[1])
    pct = float(sys.argv[2]) if len(sys.argv) > 2 else None
    result = score_batch(input_df, capacity_pct=pct)
    result.to_csv("call_list.csv", index=False)
    print(f"Wrote {len(result)} rows -> call_list.csv")
